### ISSUE TITLE
Error with command: py -m pip install -r runtime.txt

### ISSUE THREAD

**Issue by mohamedmehdigara** [ashutoshkrris/Flask-URL-Shortener#4]
**ERROR: Could not find a version that satisfies the requirement python-3.9.9 (from versions: none)ERROR: No matching distribution found for python-3.9.9**

**Comment by ashutoshkrris** [comment]
To install dependencies, you need to run:
```bash
pip install -r requirements.txt
```

But since the project uses Pipenv to manage the environment, you can follow the **Create the Virtual Environment and Install the Dependencies** section in the tutorial: https://ashutoshkrris.hashnode.dev/how-to-create-a-url-shortener-using-flask#heading-create-the-virtual-environment-and-install-the-dependencies
